name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore solution
      run: dotnet restore estudos_csharp.sln

    - name: Build solution
      run: dotnet build estudos_csharp.sln --configuration Release
